apiVersion: apps/v1
kind: Deployment
metadata:
  name: "app-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      component: "app"
  template:
    metadata:
      labels:
        component: "app"
    spec:
      containers:
      - name: "main"
        image: "finleymcilwaine/marlowe-prod:v21"
        ports:
        - containerPort: 8009
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:666739205128:certificate/87aa35b9-b1d0-4fa2-a7a7-b09330427235
spec:
  selector:
    component: "app"
  ports:
    - name: http
      port: 80
      targetPort: 8009
    - name: https
      port: 443
      targetPort: 8009
  type: LoadBalancer